### ISSUE TITLE
Working R version?

### ISSUE THREAD

**Issue by subhadeepkaran** [redichh/ShapleyR#25]
It seems I am not able to install the ShapleyR on R which is on version 3.5 and Windows 10 platform.

Using the specified method to install it 
```
install.packages("devtools")
devtools::install_github('redichh/shapleyR')
library(shapleyR)
```

It crashes with the following message:
`Error in library(shapleyR) : there is no package called ‘shapleyR’`

**Comment by redichh** [comment]
I've fixed a typo in the DESCRIPTION. This should fix the problem. Please try again to run the above lines of code and close this issue if it works for you, too.
