### ISSUE TITLE
installation read.dcf() error

### ISSUE THREAD

**Issue by lukedolezal** [redichh/ShapleyR#28]
When I try to install shapleyR in R3.5.2, I get the following error:
```
> devtools::install_github('redichh/shapleyR')
Error in read.dcf(path) : 
  Found continuation line starting '    checkmate, ...' at begin of record.
```

Perhaps something doesn't like the 4 spaces at the beginning of this line in the DESCRIPTION file?  Additionally, it doesn't look like multiple lines are needed for the Depends in that file.  Perhaps the Depends could be single-line to avoid any potential issues like this?  Just speculating...  If this is not helpful, please ignore and accept my apologies.

**Comment by redichh** [comment]
Seems like with the new R version the _new line_ mixed things up. Or maybe there was a strange _white space_ character in my DESCRIPTION file. I wrote all dependencies in one line and now it seems to work. Feel free to re-open the issue if the error is still existing for you!

Nonetheless thanks for the hint!
